import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import { CircularProgress, Text } from "@chakra-ui/react";
import { useContext, useEffect } from "react";
import { useRouter } from "next/router";
import { AuthContext } from "@component/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const router = useRouter();
    const { user } = useContext(AuthContext);

    useEffect(() => {
        if (!user) {
            setTimeout(() => router.push("/login"), 3000);
        } else {
            setTimeout(() => router.push("/home"), 3000);
        }
    }, [user]);

    return (
        <>
            <Head>
                <title>Quoted</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <CircularProgress isIndeterminate color="green.300" />
                <Text mt={3} fontSize={"md"}>
                    Just a sec...
                </Text>
            </main>
        </>
    );
}
